inherit_from: .rubocop_todo.yml

Metrics/MethodLength:
  Max: 30

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 10

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 10

Metrics/LineLength:
  Max: 100
